In [3]:
import pandas as pd

df = pd.read_csv("employee_data.csv")
df.index = ["A", "B","C","D","E","F","G","H","I","J"]
print(df,type(df))

   ID     Name  Age Department  Salary
A   1    Alice   25         HR   55000
B   2      Bob   32         IT   72000
C   3  Charlie   28    Finance   48000
D   4    David   45  Marketing   91000
E   5      Eva   38         IT   65000
F   6    Frank   29    Finance   50000
G   7    Grace   41         HR   82000
H   8   Hannah   26  Marketing   47000
I   9      Ian   35         IT   75000
J  10    Julia   30    Finance   60000 <class 'pandas.core.frame.DataFrame'>

In [3]:
# METHODS

In [4]:
# df.head() # starting 5 rows
# df.tail(2) # last ke 5 rows agar () andar ko value put kiye toh utna hi output aayega
# df.sample() # random value de dega
df.info() # used to get summary of data frame
df.shape # just like tupple but isme () bracket use nhi hoga
df.describe()  # numerical columns dega
df.columns  # columns de dega
df.nunique() # unique data frame dega ko count karega

<class 'pandas.core.frame.DataFrame'>
Index: 10 entries, A to J
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   ID          10 non-null     int64
 1   Name        10 non-null     object
 2   Age         10 non-null     int64
 3   Department  10 non-null     object
 4   Salary      10 non-null     int64
dtypes: int64(3), object(2)
memory usage: 480.0+ bytes

ID            10
Name          10
Age           10
Department     4
Salary        10
dtype: int64

In [13]:
df

   ID     Name  Age Department  Salary
A   1    Alice   25         HR   55000
B   2      Bob   32         IT   72000
C   3  Charlie   28    Finance   48000
D   4    David   45  Marketing   91000
E   5      Eva   38         IT   65000
F   6    Frank   29    Finance   50000
G   7    Grace   41         HR   82000
H   8   Hannah   26  Marketing   47000
I   9      Ian   35         IT   75000
J  10    Julia   30    Finance   60000

In [4]:
# AQI Data set 
df = pd.read_csv("globalAirQuality.csv")

# df.describe()
df1 = df.sort_values("aqi")
print(df1)

                        timestamp country           city  latitude  longitude  \
960    2025-11-14 18:25:17.554219      GB         London    51.507     -0.128
15279  2025-11-11 09:25:17.554219      US  San Francisco    37.775   -122.419
9914   2025-11-12 20:25:17.554219      CN       Shanghai    31.230    121.474
533    2025-11-11 23:25:17.554219      US    Los Angeles    34.052   -118.244
10997  2025-11-12 23:25:17.554219      TH        Bangkok    13.756    100.502
...                           ...     ...            ...       ...        ...
8941   2025-11-17 07:25:17.554219      JP          Osaka    34.694    135.502
14555  2025-11-11 05:25:17.554219      PH         Manila    14.600    120.984
745    2025-11-05 19:25:17.554219      GB         London    51.507     -0.128
12956  2025-11-19 14:25:17.554219      NZ       Auckland   -36.848    174.763
17529  2025-11-15 03:25:17.554219      FI       Helsinki    60.170     24.938

          pm25    pm10     no2    so2      o3     co  aqi  temperature  \
960      8.120  11.816   6.109  4.207  47.636  0.580   16       34.853
15279   13.087   7.782   8.638  3.500  51.672  0.294   26       17.194
9914     1.471  16.137  11.068  3.256  40.534  1.091   27        9.749
533     13.750  22.987   9.348  5.963  42.148  1.116   27       23.191
10997    8.853  27.697   6.859  4.289  27.970  0.670   27       19.872
...        ...     ...     ...    ...     ...    ...  ...          ...
8941   102.142  95.204  41.688  7.806  28.951  0.753  204       15.277
14555  103.023  66.678  43.284  2.167  48.250  0.849  206       11.027
745    107.144  43.819  13.389  4.601  21.680  0.890  214       19.055
12956   44.824  66.657  90.019  3.637  41.311  0.849  225       14.872
17529  115.683  81.714  54.764  6.687  39.552  0.685  231       25.795

       humidity  wind_speed
960      83.337       2.127
15279    33.030       3.104
9914     53.418       8.656
533      74.563       1.897
10997    34.930       3.871
...         ...         ...
8941     76.131       4.586
14555    63.522       7.635
745      66.245       1.637
12956    63.319       0.958
17529    87.839       6.705

[18000 rows x 15 columns]

In [17]:
df

   ID     Name  Age Department  Salary
A   1    Alice   25         HR   55000
B   2      Bob   32         IT   72000
C   3  Charlie   28    Finance   48000
D   4    David   45  Marketing   91000
E   5      Eva   38         IT   65000
F   6    Frank   29    Finance   50000
G   7    Grace   41         HR   82000
H   8   Hannah   26  Marketing   47000
I   9      Ian   35         IT   75000
J  10    Julia   30    Finance   60000

In [5]:
# Selecting data
# COLUMNS VALUES KO ISS TARAH KARTE HAI 
df["city"] # saare city ko ouput de dega

df[["city","aqi"]] # multiple variables ko print karne ke liye double []  lagana important hai

# ROW VALUES KO ISS TARAH
df.loc[0:3 , "city"]  # [] iske andar values row no. ko define karengi (3 inclusive rahega)

# df.iloc[0:3 , "city"]   # error aa jaega because city is string and iloc support numerical values only

# # df.iloc[0:2]  # this id for columns

# # isme index se data lete sakte hai (2 exclusive rahega)

# df.columns  # yaha se pta chala ki city ka serial no 2 then

# df.iloc[0:3 ,2] # ab ye sahi hai

# #   INDIVISUALS CELLS - rows,columns
df.loc[0 ,"aqi"]
df.loc[0:2,["country","city","aqi","longitude","latitude"]]
df.iloc[0:3 ,1:6]

# SINGLE SCALAR VALUE (SINGLE  ROW OR COLUMN)
df.at[0, "city"]
df.iat[0, 2]
## IF ORIGINAL DATA KO  CHANGE KARNE CHAHTE HAI TOH
cities = df["city"]
cities[0] = "New York"
print(cities)


# If original data ko change nhi karna chahte hai to .copy() laga do
cities = df["city"].copy()
cities[0] = "AZAMGARH"
print(cities)

0        New York
1        New York
2        New York
3        New York
4        New York
           ...
17995      Zurich
17996      Zurich
17997      Zurich
17998      Zurich
17999      Zurich
Name: city, Length: 18000, dtype: object
0        AZAMGARH
1        New York
2        New York
3        New York
4        New York
           ...
17995      Zurich
17996      Zurich
17997      Zurich
17998      Zurich
17999      Zurich
Name: city, Length: 18000, dtype: object

C:\Users\Brijesh\AppData\Local\Temp\ipykernel_23240\1703544065.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cities[0] = "New York"

In [7]:
## FILTERING OF DATA
# df[ df["aqi"] > 100]
df[(df["aqi"] >100) & (df["temperature"] >30) ].sort_values(["aqi" , "temperature"])

df[(df["aqi"] >100) & (df["temperature"] <30) ].sort_values(["aqi" , "temperature"])

aqi_data =df[df["aqi"] > 100 ] [["city", "aqi" , "temperature"]]
# print(aqi_data)

aqi_data.iloc[0]  # this is for normal indexing
aqi_data.loc[6]  # this is for default indexing  randomly choosen from list

# IF WE WANT TO CORRECT THE INDEXING VALUE THEN 
aqi_data.reset_index(drop= True) 


# QUERY METHOD  cpoy return karta hai

df.query("aqi>100 & temperature>30")

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
6,2025-11-05 00:25:17.554219,US,New York,40.713,-74.006,77.690,65.198,20.302,7.641,62.687,0.734,155,36.729,47.651,4.542
7,2025-11-05 01:25:17.554219,US,New York,40.713,-74.006,57.816,111.709,34.533,6.945,41.304,0.771,115,37.891,53.314,7.605
14,2025-11-05 08:25:17.554219,US,New York,40.713,-74.006,38.815,121.394,25.969,4.112,44.730,1.124,121,34.481,81.790,3.576
17,2025-11-05 11:25:17.554219,US,New York,40.713,-74.006,63.552,57.838,13.754,4.427,42.251,0.997,127,36.193,62.906,7.097
25,2025-11-05 19:25:17.554219,US,New York,40.713,-74.006,56.954,75.045,29.837,9.541,54.198,1.170,113,31.289,43.279,5.264
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17947,2025-11-17 13:25:17.554219,CH,Zurich,47.377,8.542,53.938,75.183,16.255,7.263,67.244,0.457,107,32.584,81.544,7.101
17950,2025-11-17 16:25:17.554219,CH,Zurich,47.377,8.542,70.255,60.620,32.081,2.065,47.803,0.852,140,36.885,34.173,1.748
17975,2025-11-18 17:25:17.554219,CH,Zurich,47.377,8.542,33.406,98.160,44.654,0.807,45.160,0.737,111,30.761,76.073,3.570
17976,2025-11-18 18:25:17.554219,CH,Zurich,47.377,8.542,73.493,89.558,9.313,4.768,51.505,0.745,146,30.909,81.573,1.024
17991,2025-11-19 09:25:17.554219,CH,Zurich,47.377,8.542,52.120,71.160,35.405,7.752,39.811,0.878,104,32.556,31.372,2.787

In [46]:
df

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
0,2025-11-04 18:25:17.554219,US,New York,40.713,-74.006,50.295,108.938,27.998,6.539,52.568,1.096,108,18.504,70.168,3.725
1,2025-11-04 19:25:17.554219,US,New York,40.713,-74.006,32.083,63.043,36.120,4.021,43.536,1.075,90,5.838,80.088,8.969
2,2025-11-04 20:25:17.554219,US,New York,40.713,-74.006,42.250,82.553,26.935,9.538,23.320,0.977,84,31.833,62.783,9.650
3,2025-11-04 21:25:17.554219,US,New York,40.713,-74.006,30.403,79.951,63.536,7.609,31.369,0.230,158,23.140,89.153,8.956
4,2025-11-04 22:25:17.554219,US,New York,40.713,-74.006,21.083,66.423,38.997,6.919,45.615,1.085,97,13.632,76.499,4.017
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17995,2025-11-19 13:25:17.554219,CH,Zurich,47.377,8.542,27.899,74.179,41.474,6.677,50.869,1.028,103,7.079,52.443,7.452
17996,2025-11-19 14:25:17.554219,CH,Zurich,47.377,8.542,2.950,47.988,42.235,2.821,35.551,0.644,105,28.734,85.678,4.496
17997,2025-11-19 15:25:17.554219,CH,Zurich,47.377,8.542,61.347,72.908,46.976,5.763,66.492,0.947,122,21.951,72.311,9.660
17998,2025-11-19 16:25:17.554219,CH,Zurich,47.377,8.542,40.722,95.152,32.957,5.524,53.193,0.868,95,24.042,31.880,2.642
17999,2025-11-19 17:25:17.554219,CH,Zurich,47.377,8.542,25.830,30.411,35.317,4.336,66.246,0.848,88,8.529,59.104,4.403

In [15]:
# CLEANING DATA - missing  values

df = pd.read_csv("raw_data.csv")

df.isnull()  # jaha par null rahega waha par true dega otherwise false

df.isna() # both are same

df.isnull().sum() # missing value de dega

df.dropna()  # row drop  of empty cells
df.dropna(axis = 1)  # column drop

df.fillna(0)  # fill up with 0 in empty sets we can change 0 to any random value

df.["age"].fillna(df["age"])

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   0.0  Canada   Female  62000.0
3    3          Alex   0.0     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      0.0
5    5        Li Wei  27.0   China     Male  51000.0
6    6             0  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0       0     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   0.0  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA        0  58000.0

In [5]:
df

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0