PANDAS EXPORT
1. to csv
2. to excel
3. to html
4. to json
5. to sql

In [1]:
import pandas as pd
df = pd.DataFrame()

to_csv

In [2]:
df = pd.read_csv("deliveries.csv")
df.head()

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
0,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,1,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
1,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,2,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
2,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,3,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
3,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,4,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
4,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,5,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,2,2,NaN,NaN,NaN

In [3]:
temp_df  = df.groupby("batsman")["batsman_runs"].sum().reset_index()
temp_df.to_csv("batsman_run.csv" , index = False) # index = False karne se extra index remove ho gya

In [4]:
df.pivot_table(index = "batsman" , columns = "bowling_team" , values = "batsman_runs" , aggfunc = "sum")

bowling_team,Chennai Super Kings,Deccan Chargers,Delhi Capitals,Delhi Daredevils,Gujarat Lions,Kings XI Punjab,Kochi Tuskers Kerala,Kolkata Knight Riders,Mumbai Indians,Pune Warriors,Rajasthan Royals,Rising Pune Supergiant,Rising Pune Supergiants,Royal Challengers Bangalore,Sunrisers Hyderabad
batsman,,,,,,,,,,,,,,,
A Ashish Reddy,45.0,NaN,NaN,36.0,NaN,37.0,NaN,17.0,27.0,26.0,37.0,NaN,NaN,55.0,NaN
A Chandila,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,NaN
A Chopra,NaN,35.0,NaN,13.0,NaN,2.0,NaN,NaN,1.0,NaN,NaN,NaN,NaN,2.0,NaN
A Choudhary,NaN,NaN,NaN,NaN,15.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0
A Dananjaya,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
YV Takawale,19.0,5.0,NaN,14.0,NaN,0.0,NaN,85.0,NaN,NaN,69.0,NaN,NaN,NaN,NaN
Yashpal Singh,NaN,NaN,NaN,13.0,NaN,NaN,NaN,NaN,8.0,NaN,26.0,NaN,NaN,NaN,NaN
Younis Khan,NaN,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Yuvraj Singh,345.0,118.0,59.0,459.0,13.0,260.0,8.0,386.0,275.0,NaN,384.0,47.0,23.0,340.0,48.0
Z Khan,39.0,4.0,NaN,4.0,NaN,1.0,NaN,20.0,5.0,NaN,18.0,NaN,NaN,25.0,1.0

to_excel

In [5]:
temp_df  = df.groupby("batsman")["batsman_runs"].sum().reset_index()

In [6]:
temp_df.to_excel("batsman.xlsx")

In [13]:
temp_df.to_excel("batsman.xlsx" , sheet_name = "batsman_runs")

In [15]:
temp_df2 = df.pivot_table(index = "batsman" , columns = "bowling_team" , values = 'batsman_runs' , aggfunc = "sum")

In [17]:
with pd.ExcelWriter("output.xlsx") as writer :
    temp_df.to_excel(writer , sheet_name = "Sheet_name_1")
    temp_df2.to_excel(writer , sheet_name = "Sheet_name_2")

to _html

In [18]:
df

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
0,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,1,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
1,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,2,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
2,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,3,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
3,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,4,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
4,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,5,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,2,2,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
179073,11415,2,Chennai Super Kings,Mumbai Indians,20,2,RA Jadeja,SR Watson,SL Malinga,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
179074,11415,2,Chennai Super Kings,Mumbai Indians,20,3,SR Watson,RA Jadeja,SL Malinga,0,...,0,0,0,0,2,0,2,NaN,NaN,NaN
179075,11415,2,Chennai Super Kings,Mumbai Indians,20,4,SR Watson,RA Jadeja,SL Malinga,0,...,0,0,0,0,1,0,1,SR Watson,run out,KH Pandya
179076,11415,2,Chennai Super Kings,Mumbai Indians,20,5,SN Thakur,RA Jadeja,SL Malinga,0,...,0,0,0,0,2,0,2,NaN,NaN,NaN
179077,11415,2,Chennai Super Kings,Mumbai Indians,20,6,SN Thakur,RA Jadeja,SL Malinga,0,...,0,0,0,0,0,0,0,SN Thakur,lbw,NaN

In [24]:
df.query("batsman_runs == 6").pivot_table(index = "over" , columns = "ball" , values = "batsman_runs" , aggfunc = "count").to_html("sixes_heatmap.html")

to json

In [27]:
df.groupby(["batting_team" , "batsman"])["batsman_runs"].sum().unstack().to_json("ipl.json")

to_sql